# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20170307_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
    ]
