# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_sensor_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
