# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20170304_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='trigger',
        ),
        migrations.DeleteModel(
            name='Capture',
        ),
    ]
