# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_sensor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
