# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0002_trigger_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor'),
        ),
    ]
